#!/bin/bash
#

module load python
module load R/4.3.1

#
workerdir=worker$1
#
mkdir -p $MEMDIR/mou_bm2/$workerdir
#
cp -r template/* $MEMDIR/mou_bm2/$workerdir/
#
cd $MEMDIR/mou_bm2/$workerdir
#

./pestpp-mou mou_bm2.pst /H c065:4019
