#!/bin/bash
#

module load python
module load R/4.3.1

#
workerdir=worker$1
#
mkdir -p $MEMDIR/mou_bm3/$workerdir
#
cp -r template/* $MEMDIR/mou_bm3/$workerdir/
#
cd $MEMDIR/mou_bm3/$workerdir
#

./pestpp-mou mou_bm3.pst /H c004:4017
